global:
  scrape_interval: 15s  # Frequency of metric scraping

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'worker1.k0s.ayo'  # 
    static_configs:
      - targets: ['213.109.146.206:9100'] 